version: '3.8'

services:
  imgbed:
    image: marseventh/cloudflare-imgbed:latest
    ports:
      - "7658:8080"
    volumes:
      - ./wrangler.jsonc:/app/wrangler.jsonc
      - ./data:/app/data
    restart: unless-stopped
